name: learn-github-actions
#run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      stacks:
        description: 'Deployment stacks'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - stack1
        - stack2
        - stack3
        - stack4
        - stack5
        - stack6
        - stack7
        - stack8
      #tags:
      #  description: 'Test scenario tags'
      #  required: false
      #  type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
env:
  SERVICE_NAME: gitops-cicd

jobs:
  mock-build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Stack: $STACK"
          echo "Environment: $ENVIRONMENT"
          echo "EventName: ${{ github.event_name }}"
        if: github.event_name != 'push'
        name: log-inputs
        env:
          STACK: ${{ inputs.stacks }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
      - run: |
          echo "EventName: ${{ github.event_name }}"
        name: log-push
        if: github.event_name == 'push'
  deploy-manul:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    needs: mock-build
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
      - uses: actions-tools/yaml-outputs@v2
        id: yaml
        with:
          file-path: 'cicd.yaml'
      - run: |
          echo "${{ steps.yaml.outputs.deployment_stacks }}"
          echo "${{ steps.yaml.outputs.test_phases }}"
      - name: Checkout configuration repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
          repository: rickliang0632/gitops-configuration
          path: gitops-config
      - name: Update Image Tag Values
        run: |
          new_image_tag=${GITHUB_SHA:0:10}
          workload_dir="workload"

          # Update the values.yaml file with the new image tag
          sed -i "s/^          image: gitops-cicd:.*/          image: gitops-cicd:$new_image_tag/" "$workload_dir/$SERVICE_NAME/deployment.yaml"
        working-directory: gitops-config
      - name: Commit the changes made
        run: |
          git config --global user.name 'Rick Liang'
          git config --global user.email 'rickliang@seismic.com'
          git commit -am "updating image tag"
          git status
          git push
        working-directory: gitops-config
  deploy-auto-non-prod:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: mock-build
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
      - uses: actions-tools/yaml-outputs@v2
        id: yaml
        with:
          file-path: 'cicd.yaml'
      - run: |
          echo "${{ steps.yaml.outputs.deployment_stacks }}"
          echo "${{ steps.yaml.outputs.test_phases }}"
      - name: Checkout configuration repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
          repository: rickliang0632/gitops-configuration
          path: gitops-config
      - name: Update Image Tag Values
        run: |
          new_image_tag=${GITHUB_SHA:0:10}
          workload_dir="workload"

          # Update the values.yaml file with the new image tag
          sed -i "s/^          image: gitops-cicd:.*/          image: gitops-cicd:$new_image_tag/" "$workload_dir/$SERVICE_NAME/deployment.yaml"
        working-directory: gitops-config
      - name: Commit the changes made
        run: |
          git config --global user.name 'Rick Liang'
          git config --global user.email 'rickliang@seismic.com'
          git commit -am "updating image tag"
          git status
          git push
        working-directory: gitops-config
  deploy-promote-prod:
    if: github.event_name != 'push' && env.ENVIRONMENT == 'production'
    runs-on: ubuntu-latest
    needs: mock-build
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
      - uses: actions-tools/yaml-outputs@v2
        id: yaml
        with:
          file-path: 'cicd.yaml'
      - run: |
          echo "${{ steps.yaml.outputs.deployment_stacks }}"
          echo "${{ steps.yaml.outputs.test_phases }}"
      - name: Checkout configuration repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
          repository: rickliang0632/gitops-configuration
          path: gitops-config
      - name: Update Image Tag Values
        run: |
          new_image_tag=${GITHUB_SHA:0:10}
          workload_dir="workload"

          # Update the values.yaml file with the new image tag
          sed -i "s/^          image: gitops-cicd:.*/          image: gitops-cicd:$new_image_tag/" "$workload_dir/$SERVICE_NAME/deployment.yaml"
        working-directory: gitops-config
      - name: Commit the changes made
        run: |
          export HEAD_BRANCH="deploy/update-${SERVICE_NAME}-image-tag-${GITHUB_SHA:0:10}"
          echo "HEAD_BRANCH=${HEAD_BRANCH}" >> $GITHUB_ENV

          git config --local user.email "rickliang@github.com"
          git config --local user.name "${{ github.actor }}"
          git switch -c ${HEAD_BRANCH}
          git add .
          git commit -m "update image tag with ${GITHUB_SHA:0:10}"
          git push -u origin ${HEAD_BRANCH}
        working-directory: gitops-config
      - name: open PR
        run: gh pr create --title "[${SERVICE_NAME}] updated image tag with ${GITHUB_SHA:0:10}" --base main --head ${HEAD_BRANCH} --body "" -r ricliang0632
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
